[package]
name = "pbsfm-rss-feed"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41" , features = ["serde"]}
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
serde = "1.0.219"

[dev-dependencies]
httpmock = "0.7.0-rc.1"
