name: Build a new CLI release

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'config/**'
      - '.github/workflows/fetch-feeds.yml'
      - '.github/workflows/jekyll.yml'
      - '.gitignore'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --release
      - name: Tar executable to preserve permissions
        run: tar -cvf pbsfm-rss-feed.tar target/release/pbsfm-rss-feed
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: pbsfm-rss-feed
          path: pbsfm-rss-feed.tar
