name: Fetch and create RSS feeds

on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: actions/checkout@v4
      - name: Download cli
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: pbsfm-rss-feed
          path: ./target/release
          run-id: 17527007883
      - name: list contents
        run: ls -R ./target/release
      - name: Run CLI
        run: ./pbsfm-rss-feed --help