name: Fetch and create RSS feeds

on:
  workflow_dispatch:
  schedule:
    - cron: 0 22 * * *

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    outputs:
      rss_changed: ${{ steps.autocommit.outputs.changes_detected }}
      new_commit_hash: ${{ steps.autocommit.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v4
      - name: Download CLI from releases
        run: |
          gh release download $CLI_RELEASE_TAG --dir ./target/release
        env:
          CLI_RELEASE_TAG: 411bbfe
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: untar executable
        run: tar -xvf ./target/release/pbsfm-rss-feed.tar
      - name: Run CLI
        run: ./target/release/pbsfm-rss-feed @config/programs.arg --output-dir docs/feeds/
      - id: autocommit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          file_pattern: docs/feeds/
  deploy-jekyll-site:
    needs: [fetch]
    uses: ./.github/workflows/jekyll.yml
    if: needs.fetch.outputs.rss_changed == 'true'
    with:
      git-ref: ${{ needs.fetch.outputs.new_commit_hash }}
    permissions:
      contents: read
      pages: write
      id-token: write
